# Generated by Django 5.0 on 2023-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='имя')),
                ('middle_name', models.CharField(max_length=25, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=25, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='почта')),
                ('message', models.TextField(blank=True, null=True, verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
